config/routes.rb
Rails.application.routes.draw do

  root 'forecasts#query'

  resources :forecasts, only: [:index, :show], param: :city do
    collection do
      get :query
    end
  end
end

app/models/forecast.rb
class Forecast
  include ActiveModel::Model

  attr_accessor :created_at, :timestamp, :temperature, :min_temperature,
                :max_temperature, :night_temperature, :evening_temperature,
                :morning_temperature, :pressure, :humidity, :description,
                :wind_speed, :wind_direction, :cloudiness

  def self.fetch!(options = {})
    options[:count] ||= 16
    hash = get_forecast_hash options

    return nil unless hash

    hash['list'].map { |item| initialize_from_hash(item) } if hash['list']
  end

  def self.fetch_one!(options = {})
    options[:count] ||= 16
    hash = get_forecast_hash options

    return nil unless hash

    list = hash['list']
    list = list.select{ |item| item['dt'] == options[:timestamp] } if list && options[:timestamp]

    initialize_from_hash list.first if list
  end

  def self.initialize_from_hash(hash = {})
    Forecast.new created_at: Time.at(hash['dt']),
                 timestamp: hash['dt'],

                 temperature: hash['temp']['day'].to_i,
                 min_temperature: hash['temp']['min'].to_i,
                 max_temperature: hash['temp']['max'].to_i,
                 night_temperature: hash['temp']['night'].to_i,
                 evening_temperature: hash['temp']['eve'].to_i,
                 morning_temperature: hash['temp']['morn'].to_i,

                 pressure: hash['pressure'].to_i,
                 humidity: hash['humidity'].to_i,

                 description: (hash['weather'].first['description'] if hash['weather'].first),

                 wind_speed: hash['speed'].to_i,
                 wind_direction: hash['deg'].to_i,
                 cloudiness: hash['clouds'].to_i
  end

  private

  def self.get_forecast_hash(options = {})
    count = options[:count] || 1
    city = options[:city] || 'Dublin, IE'

    begin
      OpenWeather::ForecastDaily.city(city, units: 'metric', cnt: count, APPID: Rails.application.secrets.open_weather_appid)
    rescue
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def index
    @city = params[:city]

    @forecasts = Forecast.fetch! city: @city
  end

  def show
    @city = params[:city]
    @timestamp = params[:timestamp].to_i

    @forecast = Forecast.fetch_one! city: @city, timestamp: @timestamp
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forecasts/_forecast.html.haml
= link_to forecast_path(city: @city, timestamp: forecast.timestamp), class: 'forecast' do
  .forecast__title
    = forecast.created_at.to_s :forecast_day
  .forecast__temperature
    = "#{forecast.temperature}°"
  - if forecast.description
    .forecast__description
      = forecast.description.capitalize
  .forecast__minmax
    = "#{forecast.min_temperature}° - #{forecast.max_temperature}°"
  .forecast__humidity
    = "Humidity: #{forecast.humidity}%"
  .forecast__wind-speed
    = "Wind speed: #{forecast.wind_speed} m/s"

app/views/forecasts/index.html.haml
%h1.title
  Forecast for
  %span.title__city= @city

- if @forecasts
  .forecasts
    = render @forecasts
- else
  .error
    Unable to get forecast data. OpenWeatherMap might be down or your query might have failed.

= link_to '<< New query', root_path, class: 'back-link'

app/views/forecasts/query.html.haml
= form_tag forecasts_url, method: :get, class: 'forecast-form' do
  = text_field_tag :city, nil, class: 'forecast-form__city', required: true, placeholder: 'Enter city'
  %br
  = submit_tag 'Get forecast', class: 'forecast-form__submit'

app/views/forecasts/show.html.haml
%h1.title
  Forecast for
  %span.title__city= @city
  on
  %span.title__date= Time.at(@timestamp).to_s :forecast_day

- if @forecast
  %ul.forecast-detail
    - if @forecast.description
      %li= @forecast.description.capitalize
    %li= "Temperature: #{@forecast.temperature}°"
    %li= "Min temperature: #{@forecast.min_temperature}°"
    %li= "Max temperature: #{@forecast.max_temperature}°"
    %li= "Night temperature: #{@forecast.night_temperature}°"
    %li= "Evening temperature: #{@forecast.evening_temperature}°"
    %li= "Morning temperature: #{@forecast.morning_temperature}°"
    %li= "Pressure: #{@forecast.pressure} hPa"
    %li= "Humidity: #{@forecast.humidity}%"
    %li= "Wind speed: #{@forecast.wind_speed} m/s"
    %li= "Wind direction: #{@forecast.wind_direction}°"
    %li= "Cloudiness: #{@forecast.cloudiness}%"
- else
  .error
    Unable to get forecast data. OpenWeatherMap might be down or your query might have failed.

= link_to "<< Forecast for #{@city}", forecasts_path(city: @city), class: 'back-link'

app/views/layouts/_footer.html.haml
%footer.footer
  .footer__wrapper
    = link_to 'Forecastie', root_path, class: 'footer__link'
    Created by Attila Horváth in 2016
    = link_to 'Fork it on GitHub', 'https://github.com/attilahorvath/forecastie', class: 'footer__link footer__github'

app/views/layouts/_header.html.haml
%header.header
  = link_to 'Forecastie', root_path, class: 'header__link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Forecastie
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'